custom_components/solis/manifest.json, custom_components/solis/platform2_portal.py, custom_components/solis/sensor.py
Reduced error messages and closes #2 and closes #3
=> Fix issue 2 and 3

custom_components/solis/manifest.json, custom_components/solis/platform2_portal.py, custom_components/solis/sensor.py
HTTP statuses have been removed from homeassistant.const. Move to using HTTPStatus from http.
=> 38 cannot import http ok

custom_components/solis/ginlong_api.py, custom_components/solis/manifest.json, custom_components/solis/sensor.py, custom_components/solis/service.py
=> 53 54 robustness issues

custom_components/solis/sensor.py, custom_components/solis/soliscloud_api.py
Couple of fixes as requested.
The result_json structures were not as you expected, and I've added the URI to the error message in the POST to try and help with diagnostics.
The body of the POST can actually remain as json= as that does actually work when I have the right Domain :grin:
=> 18 soliscloud api support

custom_components/solis/soliscloud_api.py
Fix Precisions for the Power Sensors - They are in kW so 0.xxx, I'm converting to W in the post processing function
The API has a typo either in the doc or in the implmentation GRID_TOTAL_POWER is psum not pSum
pacPec is Power percentage not INVERTER_POWER_LIMIT (I've only ever seen it at 1 so I removed it for now)
BAT_REMAINING_CAPACITY is indeed batteryCapacitySoc
My API calls return 32 Strings but my inverter only has the capability for 2.  Unfortunately both no string present and the string not generating anything have the relivant fields at 0 so doing a simple purge if unused doesn't work, there is a dcInputtype field which is number of strings - 1 so we'll need to do something with that to get rid of unused strings.
=> Fix Precisions and convert Power from kW to W

custom_components/solis/soliscloud_api.py, custom_components/solis/soliscloud_const.py
Removing unused dc strings based on dcInputtype
Only converting kW to W based on the appropriate Power String
I'm not 100% happy with the way I've delt with the unused DC Strings but it works with the existing purge_if_unused function.
=> Update post processor

custom_components/solis/ginlong_api.py, custom_components/solis/service.py
=> 54 energy today robustness

custom_components/solis/ginlong_api.py
Introduce robustness against crashes due to invalid data from server
=> Add data integrity check

custom_components/solis/ginlong_api.py
Fix unsuccessful data capture due to missing timestamp
=> Add key tests on timestamps

custom_components/solis/sensor.py, custom_components/solis/service.py
Instead of 3 retries, just trigger discovery at end of setup and let the discovery retry every 60 seconds until successful. Once successful initialize the sensors and register them
=> 69 fix retry mechanism

custom_components/solis/ginlong_api.py
Convert to W in case of unit = kW
=> 56 fix variable power unit

test/soliscloud_test.py
Added some comments to help id the right details to fill in.
Added comments and cleaned up code to help with endpoint/body selection
Added some more url endpoints and appropriate bodies.
Commented out some optional debug output.
Added some additional output format options.
=> Improvements and Cleanup to test code

custom_components/solis/soliscloud_api.py, custom_components/solis/soliscloud_const.py
Did some unit conversions for things in kW that need to be in Watts and stuff in MWh and GWh into kWh.
I know you wanted to have a standardised way to do this but this is just a quick fix to make it work for now.
=> Fixing Some Units

custom_components/solis/const.py, custom_components/solis/ginlong_const.py, custom_components/solis/soliscloud_api.py, custom_components/solis/soliscloud_const.py
- Added Battery power
- Temp Fix for Export to Grid being out by a factor of 10
- Fix some case inconsistancies in sensor names (sorry my OCD is kicking in 😁)
- breaking change  will need old sensors removed and new ones will "need" to have their Entity ID's renamed to remove the _2 from them.
=> Adding Battery Power

custom_components/solis/const.py, custom_components/solis/manifest.json, custom_components/solis/sensor.py
Removal of deprecated configuration.
Also made config check more robust, moving check from startup time to HA config check.
=> 30 remove deprecated config

custom_components/solis/soliscloud_api.py
Got fed up with Energy Today dropping to 0 at 16:00 UTC 😄 so added a fetch of stationDetail and using the dayEnergy from that Response.
=> Change Source of Energy Today to stationDetail

custom_components/solis/ginlong_api.py, custom_components/solis/manifest.json, custom_components/solis/sensor.py, custom_components/solis/service.py, custom_components/solis/soliscloud_api.py
Fixes #109, #123, #125, #132, #133, #135, #137, #138
=> 109 123 125 132 133 135 137 138 bug fixes

custom_components/solis/manifest.json, custom_components/solis/sensor.py, custom_components/solis/soliscloud_api.py
Remove AddUser call to work around current API blockade
=> 162 no data after soliscloud update am 2709

custom_components/solis/manifest.json, custom_components/solis/sensor.py, custom_components/solis/soliscloud_api.py
Added robustness in post-processing
=> 166 crash after upgrade 235

custom_components/solis/config_flow.py, custom_components/solis/manifest.json, custom_components/solis/sensor.py
=> 171 registering soliscloud via UI reports typeerror

custom_components/solis/config_flow.py, custom_components/solis/manifest.json, custom_components/solis/sensor.py
=> 173 soliscloud invalid credentials

custom_components/solis/strings.json, custom_components/solis/translations/en.json
=> 186 new entity names created when installing new release 307 rather than reuse of existing

custom_components/solis/ginlong_api.py, custom_components/solis/manifest.json, custom_components/solis/sensor.py
=> 180 the integration stops retrieving data from the server 2

custom_components/solis/manifest.json, custom_components/solis/sensor.py
=> 205 still having trouble with integration not updating on 3010

custom_components/solis/ginlong_api.py, custom_components/solis/manifest.json, custom_components/solis/sensor.py
Closes #213 
* Add notification when stale inverter is ignored
* Catch StopIteration
=> 213 cannot login unknown error occurred

custom_components/solis/__init__.py, custom_components/solis/config_flow.py, custom_components/solis/manifest.json, custom_components/solis/sensor.py, custom_components/solis/soliscloud_api.py
Closes #183 , closes #216 , closes #230
=> 216 solis energy today entity became unavailable

custom_components/solis/manifest.json, custom_components/solis/sensor.py, custom_components/solis/soliscloud_api.py, custom_components/solis/workarounds.yaml
=> 252 solis energy today the same for all 3 inverters shows plant total instead of daily per inverter

custom_components/solis/config_flow.py, custom_components/solis/const.py, custom_components/solis/ginlong_base.py
* Soliscloud now default
* Move rstrip to config
=> 277 no inverters found

custom_components/solis/soliscloud_api.py
=> Robustness against offline inverters

custom_components/solis/soliscloud_api.py
=> 279 solis daily grid energy used shows no values

custom_components/solis/soliscloud_api.py
Added precision for cases where energy is MWh
=> Improve precision

.github/workflows/autoformat.yaml
@hultenvp looks like this may fix the autoformat issue.
=> Try using checkout@v2

.github/workflows/autoformat.yaml
Based on https://github.com/actions/checkout?tab=readme-ov-file , I don't think the "ref" param is needed, and I think that's what is causing the issues.... let's try without it?
=> Try not specifying a ref

custom_components/solis/__init__.py, custom_components/solis/config_flow.py, custom_components/solis/service.py
This was a recommended tidy from isort after applying https://github.com/hultenvp/solis-sensor/pull/488 .
=> (trivial) Fix sorting order

README.md, custom_components/solis/config_flow.py, custom_components/solis/strings.json, custom_components/solis/translations/en.json
This aligns the strings in the config panel with those in the SolisCloud UI, for better consistency; it also ensures the username/keyid/keysecret fields appear in the "normal" order.  Also, the control API is called "Inverter control" in SolisCloud, so let's line that up.
=> Improve config text strings
